steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/bucks-xchange-rates/xchange:${SHORT_SHA}', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/bucks-xchange-rates/xchange"]
timeout: "1600s"
