steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/xchange:${SHORT_SHA}', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/$PROJECT_ID/xchange"]
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', 'xchange', '--image', 'gcr.io/$PROJECT_ID/xchange:${SHORT_SHA}', '--region', 'europe-west1', '--platform', 'managed']
timeout: "1600s"
